package com.onevour.core;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import androidx.test.ext.junit.runners.AndroidJUnit4;

import com.onevour.core.rest.UserRepository;
import com.onevour.core.rest.UserRequest;
import com.onevour.core.rest.UserResponse;
import com.onevour.core.rest.builder.GeneratedRepository;
import com.onevour.core.rest.builder.RestClient;
import com.onevour.core.rest.listener.HttpListener;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;

import java.lang.reflect.Proxy;
import java.util.List;
import java.util.concurrent.TimeUnit;
import java.util.function.Consumer;

import okhttp3.mockwebserver.MockResponse;
import okhttp3.mockwebserver.MockWebServer;
import okhttp3.mockwebserver.RecordedRequest;

/**
 * The repository code generated by commons-sdk-processor sends exactly the request the Proxy sends,
 * for every method of UserRepository: verb, path with query, headers, body.
 */
@RunWith(AndroidJUnit4.class)
public class RestGeneratedParityTest {

    private MockWebServer server;

    private final UserRepository generated = new RestClient().create(UserRepository.class);

    private final UserRepository proxy = new RestClient(false).create(UserRepository.class);

    @Before
    public void setUp() throws Exception {
        server = new MockWebServer();
        server.start(3000);
    }

    @After
    public void tearDown() throws Exception {
        server.shutdown();
    }

    @Test
    public void restClient_usesTheGeneratedCode_andTheProxyOnlyWhenAsked() {
        assertTrue(generated instanceof GeneratedRepository);
        assertFalse(Proxy.isProxyClass(generated.getClass()));
        assertTrue(Proxy.isProxyClass(proxy.getClass()));
    }

    /** The same call through both: the two requests the server got. */
    private void same(Consumer<UserRepository> call) throws Exception {
        server.enqueue(new MockResponse().setResponseCode(200).setHeader("Content-Type", "application/json").setBody("{\"id\":1,\"name\":\"a\"}"));
        server.enqueue(new MockResponse().setResponseCode(200).setHeader("Content-Type", "application/json").setBody("{\"id\":1,\"name\":\"a\"}"));
        call.accept(proxy);
        RecordedRequest expected = server.takeRequest(5, TimeUnit.SECONDS);
        call.accept(generated);
        RecordedRequest actual = server.takeRequest(5, TimeUnit.SECONDS);
        assertNotNull(expected);
        assertNotNull(actual);
        assertEquals(expected.getMethod(), actual.getMethod());
        assertEquals(expected.getPath(), actual.getPath());
        assertEquals(expected.getHeader("Content-Type"), actual.getHeader("Content-Type"));
        assertEquals(expected.getHeader("Authorization"), actual.getHeader("Authorization"));
        assertEquals(expected.getHeader("User-Agent"), actual.getHeader("User-Agent"));
        assertEquals(expected.getBody().readUtf8(), actual.getBody().readUtf8());
    }

    @Test
    public void everyMethod_sendsTheSameRequest() throws Exception {
        UserRequest body = new UserRequest("Budi & Sari");
        same(repository -> repository.getUser("budi santoso/&?", UserRepositoryParity.<UserResponse>ignore()));
        same(repository -> repository.searchUser("budi", 2, UserRepositoryParity.<UserResponse>ignore()));
        same(repository -> repository.create(body, UserRepositoryParity.<UserResponse>ignore()));
        same(repository -> repository.update("7", body, UserRepositoryParity.<UserResponse>ignore()));
        same(repository -> repository.updateWithPost("7", body, UserRepositoryParity.<UserResponse>ignore()));
        same(repository -> repository.patch("7", body, UserRepositoryParity.<UserResponse>ignore()));
        same(repository -> repository.delete("7", UserRepositoryParity.<UserResponse>ignore()));
        same(repository -> repository.getWithTimeout(UserRepositoryParity.<UserResponse>ignore()));
        same(repository -> repository.getWithHeaders("budi", "Bearer token-1", UserRepositoryParity.<UserResponse>ignore()));
        same(repository -> repository.getObject(UserRepositoryParity.<UserResponse>ignore()));
        same(repository -> repository.getString(UserRepositoryParity.<String>ignore()));
        same(repository -> repository.getList(UserRepositoryParity.<List<UserResponse>>ignore()));
    }

    /** Typed no-op listeners for the calls above. */
    static final class UserRepositoryParity {
        static <T> HttpListener<T> ignore() {
            return HttpListener.of(response -> { }, error -> { });
        }
    }
}
