plugins {
    id 'com.android.application'
}

android {
    compileSdk = 36
    defaultConfig {
        applicationId "com.onevour.sdk.impl"
        minSdk = 23
        targetSdk = 37
        versionCode 3
        versionName "0.0.1"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildFeatures {
        viewBinding true
        dataBinding true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    testOptions {
        unitTests.returnDefaultValues = true
    }
    namespace 'com.onevour.sdk.impl'
}

dependencies {
    implementation(platform("org.jetbrains.kotlin:kotlin-bom:1.8.0"))
    implementation 'com.google.android.material:material:1.14.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.2'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    implementation 'com.google.code.gson:gson:2.10'

    implementation 'org.greenrobot:eventbus:3.3.1'
    // db
    def room_version = "2.5.2"
    implementation "androidx.room:room-runtime:$room_version"
    annotationProcessor "androidx.room:room-compiler:$room_version"
    implementation "androidx.room:room-rxjava2:$room_version" // optional - RxJava2 support for Room
    // ws
    implementation 'com.github.NaikSoftware:StompProtocolAndroid:1.6.2'
    implementation 'io.reactivex.rxjava2:rxjava:2.2.20'
    implementation project(':commons-sdk')
    implementation 'androidx.appcompat:appcompat:1.8.0'
    implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.1.0'

    // di
    implementation 'com.google.dagger:dagger-android:2.44'
    implementation 'com.google.dagger:dagger-android-support:2.44' // if you use the support libraries
    annotationProcessor 'com.google.dagger:dagger-android-processor:2.44'
    annotationProcessor 'com.google.dagger:dagger-compiler:2.44'

    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.mockito:mockito-core:4.5.1'
    androidTestImplementation 'androidx.test:runner:1.7.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'
    testImplementation group: 'org.powermock', name: 'powermock-mockito-release-full', version: '1.6.4', ext: 'pom'
    testImplementation group: 'org.powermock', name: 'powermock-module-junit4', version: '2.0.7'
}
