plugins {
    id 'com.android.library'
    id 'maven-publish'
}

// https://vtsen.hashnode.dev/how-to-publish-android-library-on-jitpackio-with-github

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release
                groupId = 'com.onevour.core'
                artifactId = 'sdk'
                version = '0.0.2'
            }
        }
    }
}

android {
    namespace 'com.onevour.core'
    compileSdk = 36
    defaultConfig {
        minSdk = 23
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    testOptions {
        unitTests.returnDefaultValues = true
    }
    buildFeatures {
        viewBinding true
        dataBinding true
    }
    publishing {
        singleVariant('release') {
            withSourcesJar()
        }
    }

}

dependencies {
    implementation 'androidx.constraintlayout:constraintlayout:2.2.2'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'com.google.android.material:material:1.14.0'
    implementation 'androidx.appcompat:appcompat:1.8.0'
    implementation 'com.google.code.gson:gson:2.10'
    implementation 'com.github.bumptech.glide:glide:4.13.1'
    implementation 'io.jsonwebtoken:jjwt:0.9.1'
    implementation 'joda-time:joda-time:2.12.5'
    implementation 'org.greenrobot:eventbus:3.3.1'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.13.1'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.mockito:mockito-core:4.5.1'
    testImplementation group: 'org.powermock', name: 'powermock-mockito-release-full', version: '1.6.4', ext: 'pom'
    testImplementation group: 'org.powermock', name: 'powermock-module-junit4', version: '2.0.7'

    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'
}